name: Upload build artifact

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  gradle_build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Upload build artifact
      uses: actions/upload-artifact@v4.6.2
